- platform: knx
  name: kitchen_street
  move_long_address: 2/3/1
  move_short_address: 2/3/2
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: kitchen_terrace
  move_long_address: 2/3/3
  move_short_address: 2/3/4
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: living_terrace
  move_long_address: 2/3/5
  move_short_address: 2/3/6
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: living_dining
  move_long_address: 2/3/7
  move_short_address: 2/3/8
  travelling_time_down: 59
  travelling_time_up: 57
- platform: knx
  name: living_balcony_door
  move_long_address: 2/3/9
  move_short_address: 2/3/10
  position_address: 2/6/145
  position_state_address: 2/5/165
  travelling_time_down: 65
  travelling_time_up: 65
  invert_position: true
- platform: knx
  name: living_tv
  move_long_address: 2/3/11
  move_short_address: 2/3/12
  travelling_time_down: 59
  travelling_time_up: 57
- platform: knx
  name: child_balcony
  move_long_address: 2/3/13
  move_short_address: 2/3/14
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: child_window
  move_long_address: 2/3/15
  move_short_address: 2/3/16
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: sleep_garage
  move_long_address: 2/3/19
  move_short_address: 2/3/20
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: sleep_street
  move_long_address: 2/3/21
  move_short_address: 2/3/22
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: bath
  move_long_address: 2/3/23
  move_short_address: 2/3/24
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: guest_bath
  move_long_address: 2/3/25
  move_short_address: 2/3/26
  travelling_time_down: 25
  travelling_time_up: 27
