- platform: knx
  name: kitchen_street
  move_long_address: 2/3/1
  move_short_address: 2/3/2
  position_address: 2/6/141
  position_state_address: 2/5/161
  angle_address: 2/6/161
  angle_state_address: 2/5/141
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: kitchen_terrace
  move_long_address: 2/3/3
  move_short_address: 2/3/4
  position_address: 2/6/142
  position_state_address: 2/5/162
  angle_address: 2/6/162
  angle_state_address: 2/5/142
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: living_terrace
  move_long_address: 2/3/5
  move_short_address: 2/3/6
  position_address: 2/6/143
  position_state_address: 2/5/163
  angle_address: 2/6/163
  angle_state_address: 2/5/143
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: living_dining
  move_long_address: 2/3/7
  move_short_address: 2/3/8
  position_address: 2/6/144
  position_state_address: 2/5/164
  angle_address: 2/6/164
  angle_state_address: 2/5/144
  travelling_time_down: 59
  travelling_time_up: 57
- platform: knx
  name: living_balcony_door
  move_long_address: 2/3/9
  move_short_address: 2/3/10
  position_address: 2/6/145
  position_state_address: 2/5/165
  angle_address: 2/6/165
  angle_state_address: 2/5/145
  travelling_time_down: 65
  travelling_time_up: 65
- platform: knx
  name: living_tv
  move_long_address: 2/3/11
  move_short_address: 2/3/12
  position_address: 2/6/146
  position_state_address: 2/5/166
  angle_address: 2/6/166
  angle_state_address: 2/5/146
  travelling_time_down: 59
  travelling_time_up: 57
- platform: knx
  name: child_balcony
  move_long_address: 2/3/13
  move_short_address: 2/3/14
  position_address: 2/6/147
  position_state_address: 2/5/167
  angle_address: 2/6/167
  angle_state_address: 2/5/147
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: child_window
  move_long_address: 2/3/15
  move_short_address: 2/3/16
  position_address: 2/6/148
  position_state_address: 2/5/168
  angle_address: 2/6/168
  angle_state_address: 2/5/148
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: sleep_garage
  move_long_address: 2/3/19
  move_short_address: 2/3/20
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: sleep_street
  move_long_address: 2/3/21
  move_short_address: 2/3/22
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: bath
  move_long_address: 2/3/23
  move_short_address: 2/3/24
  travelling_time_down: 25
  travelling_time_up: 27
- platform: knx
  name: guest_bath
  move_long_address: 2/3/25
  move_short_address: 2/3/26
  travelling_time_down: 25
  travelling_time_up: 27
- platform: mqtt
  name: "garage_door_big"
  command_topic: !secret shelley_garage_big_command
  state_topic: !secret shelley_garage_big_input
  state_open: "0"
  state_closed: "1"
  payload_open: "on"
  payload_close: "on"
  device_class: garage