- platform: mqtt
  name: "garage_door_big"
  command_topic: !secret shelley_garage_big_command
  state_topic: !secret shelley_garage_big_input
  state_open: "0"
  state_closed: "1"
  payload_open: "on"
  payload_close: "on"
  device_class: garage
- platform: mqtt
  name: "garage_door_small"
  command_topic: !secret shelley_garage_small_command
  state_topic: !secret shelley_garage_small_input
  state_open: "0"
  state_closed: "1"
  payload_open: "on"
  payload_close: "on"
  device_class: garage