- platform: knx
  name: temp_kitchen
  state_address: '2/7/10'
  type: temperature
- platform: knx
  name: temp_wz_eingang
  state_address: '2/7/11'
  type: temperature
- platform: knx
  name: temp_wz_tv
  state_address: '2/7/12'
  type: temperature
- platform: knx
  name: temp_child
  state_address: '2/7/13'
  type: temperature
- platform: knx
  name: temp_hallway
  state_address: '2/7/14'
  type: temperature
- platform: knx
  name: temp_sleep
  state_address: '2/7/15'
  type: temperature
- platform: knx
  name: temp_bath
  state_address: '2/7/16'
  type: temperature
- platform: knx
  name: temp_guest_bath
  state_address: '2/7/17'
  type: temperature
- platform: knx
  name: temp_laundry
  state_address: '2/7/18'
  type: temperature